export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_BASKET_NUMBERS = 'GET_BASKET_NUMBERS';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
